version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: serverless
      PGDATA: /data/postgres
    volumes:
      - ./.docker/postgres:/data/postgres
    networks:
      - serverless-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=development
      - MINIO_ROOT_PASSWORD=development
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.docker/minio:/data

networks:
  serverless-network:
    driver: bridge
